config/routes.rb
TheDogs::Application.routes.draw do
  get "checkout/form"
  get "/checkout/form"
  post "checkout/form"
  get "result/new"
  post "result/new"
  get "result/search"
  post "result/search"
  get "result/create"
  get "cart/new"
  get "cart/create"
  get "detail/new"
  get "detail/create"
  get "home/index"
  get "home/show"
  get "home/search"
  post "home/search"
  resources :dogs

  root 'home#index'

     

end

app/models/client.rb
class Client < ActiveRecord::Base

   attr_accessible :name, :cpf, :phone, :email, :phone
   
end

app/models/dog.rb
class Dog < ActiveRecord::Base
  
  attr_accessible :breed, :age, :name, :coat, :sex, :price, :image, :image_file_name, :image_content_type, :image_file_size, :image_updated_at

  include PgSearch 

  multisearchable :against => [:breed, :sex, :name ]

  has_attached_file :image

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates_presence_of :breed, :price

  def self.tsearch_query(search_terms, limit = query_limit)
    Dog.from("dogs, to_tsquery('pg_catalog.english') as q").where("breed @@ q").limit(limit)
  end

  # Selects search results with plain text title & body columns.
  # Select columns are explicitly listed to avoid returning the long redundant tsv strings
  def self.plain_tsearch(search_terms, limit = query_limit)
    select([:breed, :name, :sex]).tsearch_query(search_terms, limit)
  end

  # Select search results with HTML highlighted title & body columns
  def self.highlight_tsearch(search_terms, limit = query_limit)
    body = "ts_headline(body, q, 'StartSel=<em>, StopSel=</em>, HighlightAll=TRUE') as body"
    title = "ts_headline(title, q, 'StartSel=<em>, StopSel=</em>, HighlightAll=TRUE') as title"
    Dog.select([body, title, :id]).tsearch_query(search_terms, limit)
  end

  def self.query_limit; 25; end

  def image_url
    self.image.url(:thumb)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  
  before_filter :find_cart_item, :only => [:update, :destroy]
  
  def create
    persist_cart if @cart.new_record?
    @cart.add_item(find_cartable)
  end
  
  def update
    if @cart_item.update_attributes(cart_item_params)
      flash[:notice] = t(:cart_updated)
      redirect_to cart_path(cart)
    else
      flash[:notice] = t(:cart_update_failed)
    end
  end
  
  def destroy
    if @cart_item.destroy
      flash[:notice] = t(:cart_item_removed)
      redirect_to cart_path(@cart)
    else
      flash[:notice] = t(:cart_update_failed)
    end
  end
  
  protected
  
    def find_cart_item
      @cart_item = @cart.cart_items.find(params[:id])
    end

  private

    def cart_item_params
      params.require(:cart_item).permit!
    end
    
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show

  end
  
  def destroy
    cart.destroy
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def form
    @dogs = Dog.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @dogs = Dog.all
  end

  def show
    @dogs = Dog.find(params[:id])
  end

  def search
 
    @dogs = Dog.plain_tsearch(params[:search])
   
    respond_to do |format|
      format.html { render :index }
      format.js { @dogs }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/detail_helper.rb
module DetailHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/result_helper.rb
module ResultHelper
end

app/views/checkout/form.html.erb
<%= render "home/header" %>
<div class="content">
    <div class="container">
        <div class="box-cachorro checkout">
            <span class="col-md-4"><%= image_tag(@dogs.image_file_name, alt: @dogs.breed)%></span>
            <span class="col-md-4 titulo-cachorro">
                <ul class="dog-info">
                    <li>Raça: <%= @dogs.breed %></li>
                    <li>Pelagem: <%= @dogs.coat %></li>
                    <li>Idade: <%= @dogs.age %> anos </li>
                    <li>Sexo: <%= @dogs.sex %></li>
                    <li>Nome: <%= @dogs.name %></li>
                    <li>Preço: <%= @dogs.price %></li>
                </ul>
            </span>
        </div>
        <article>
          <%= form_for :client do |f| %>
            <%= label(:name, "Nome:") %>
            <%= f.text_field :name %><br/>
            <%= label(:cpf, "CPF:") %>
            <%= f.text_field :cpf %><br/>
            <%= label(:mail, "E-mail:") %>
            <%= f.email_field("mail") %><br/>
            <%= label(:phone, "Telefone:") %>
            <%= f.text_field :phone %><br/>
            <span class="btn btn-success btn-lg">
                Enviar
                <!-- <%= f.submit "Enviar" %> -->
            </span>
          <% end %>
        </article>
    </div>
</div>
<%= render "home/footer" %>

app/views/home/_footer.html.erb
<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-4">
                <ul class="list-group lista-links">
                    <li class="list-group-item">
                        <a href="#" title="mini">mini</a>
                    </li>
                    <li class="list-group-item">
                        <a href="#" title="pequeno porte">pequeno porte</a>
                    </li>
                    <li class="list-group-item">
                        <a href="#" title="médio porte">médio porte</a>
                    </li>
                    <li class="list-group-item">
                        <a href="#" title="grande porte">grande porte</a>
                    </li>
                </ul>   
            </div>

            <div class="col-lg-4 col-md-4 col-sm-4">
                <ul class="list-group lista-links">
                    <li class="list-group-item">
                        <a href="#" title="até R$100">até R$100</a>
                    </li>
                    <li class="list-group-item">
                        <a href="#" title="de R$100 a R$300">de R$100 a R$300</a>
                    </li>
                    <li class="list-group-item">
                        <a href="#" title="de R$300 a R$500">de R$300 a R$500</a>
                    </li>
                    <li class="list-group-item">
                        <a href="#" title="acima de R$500">acima d  500</a>
                    </li>
                </ul>   
            </div>

            <div class="col-lg-4 col-md-4 col-sm-4 text-right">
                <%= image_tag("logo-rodape.png", alt: "TheDogss") %>
                <br>
                <p class="telefone">11 0000.0000<br>
                    <a href="mailto:#" title="Entre em contato!">contato@charlieedog.com.br             
                </p>
            </div>
        </div>
    </div>
</div>

app/views/home/_header.html.erb
<div class="header">
    <div class="container">
        <div class="row">
            <div class="col-lg-2 col-md-2 col-sm-2">
                <a href="/" title="TheDogss"><%= image_tag("logo.svg", alt: "TheDogss") %></a>
            </div>
            <div class="col-lg-10 col-md-10 col-sm-10">           
                <div class="input-group buscar">
                <%= form_tag home_search_path, :method => :get, :remote => true do %>
                <%= text_field_tag :search, params[:search], class: "form-control input-lg" %>
                <!--<%= submit_tag "Search" %>-->
                <span class="input-group-btn">
                        <button class="btn btn-default input-lg" type="button">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </span>
                <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<body>
    <%= render "home/header" %>
    <div class="content">
        <div class="container">
           <!--  <div id="search_results">
              <% if @dogs.any? %>
                <p> ok </p>
              <% else %>
                <p>
                  Oh dear. Your search matched nothing in the database, or there there is simply
                  nothing in the database.
                </p>
              <% end %>
            </div> -->
            <div class="row">
            <% @dogs.each do |dog| %>
                <a class="fancybox" href="#">
                    <div class="col-md-4">
                        <div class="box-cachorro">
                            <%= image_tag(dog.image_file_name, alt: dog.breed)%>
                            <div class="btn-foto"><%= link_to "Detalhes", {:action => 'show', :id => dog.id} %></div>
                            <div>
                                <span class="titulo-cachorro"><%= dog.breed %> <%= dog.coat %></span>
                                <span class="detalhes-cachorro"><strong><%= dog.price %></strong><br><%= dog.age %> anos</span>
                            </div>
                        </div>
                    </div>
                </a>
            <% end %>
            </div>
        </div>
    </div>
    <%= render "home/footer" %>
</body>

app/views/home/search.js.erb
<% if @dogs.any? %>
$("#search_results").html("<%= escape_javascript(render @dogs) %>");
<% else %>
$("#search_results").html("<p>Oh dear. Your search matched nothing in the database</p>");
<% end %>

app/views/home/show.html.erb
<%= render "home/header" %>
<div class="content">
    <div class="container">
        <div class="box-cachorro detalhe">
            <span class="col-md-8"><%= image_tag(@dogs.image_file_name, alt: @dogs.breed)%></span>
            <span class="col-md-4 titulo-cachorro">
                <ul class="dog-info">
                    <li>Raça: <%= @dogs.breed %></li>
                    <li>Pelagem: <%= @dogs.coat %></li>
                    <li>Idade: <%= @dogs.age %> anos </li>
                    <li>Sexo: <%= @dogs.sex %></li>
                    <li>Nome: <%= @dogs.name %></li>
                    <li>Preço: <%= @dogs.price %></li>
                    <li>
                      <span class="btn btn-success btn-lg">
                        <%= link_to "checkout", {:controller => "checkout", :action => "form", :id => @dogs.id} %>
                      </span>
                    </li>
                </ul>
            </span>
        </div>
    </div>
</div>
<%= render "home/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheDogs</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "//code.jquery.com/jquery-2.1.3.js" %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag("//fonts.googleapis.com/css?family=Amatic+SC:400,700") %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/result/create.html.erb
<h1>Result#create</h1>
<p>Find me in app/views/result/create.html.erb</p>

app/views/result/new.html.erb
<%-@dogs.each do |dog| %>
  Raça: <%=dog.breed %>
<%- end %>